{
 "title": "Backend Services Logs",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Backend Users Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=~\"dotnetcv-users-service\"}"
    }
   ]
  },
  {
   "title": "Frontend Services Logs",
   "type": "logs",
   "gridPos": { "h": 23, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=~\"dotnetcv-frontend\"}"
    }
   ]
  },
  {
   "title": "Backend Orders Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=~\"dotnetcv-orders-service\"}"
    }
   ]
  }
 ]
}